### ISSUE TITLE
Cosmetic error when launching iPad in Landscape orientation

### ISSUE THREAD

**Issue by jpcoates** [dhennessy/PAPasscode#12]
When I launch an app using implemented PAPasscode with the iPad simulator or actual device in landscape orientation, when the passcode view is presented, it is clipped at the top.  See image. I am initiating the PAPasscodeViewController in a DetailViewController of a Master/Detail view example (using UISplitViewController).

![image](https://cloud.githubusercontent.com/assets/2286719/2544428/205f3b72-b600-11e3-84ad-3dd1b68c24da.png)

**Comment by dhennessy** [comment]
I've fixed this in version 1.0
